### ISSUE TITLE
Multi core support

### ISSUE THREAD

**Issue by g0kkk** [puppet-meteor/EMS#3]
Hi,

Does EMS support fuzzing with multiple cores? I had tried to fuzz a target with multiple cores, and every process was killed within a few minutes after fuzzing started.  

Thanks

**Comment by puppet-meteor** [comment]
Sorry, recently we are busy and may not be free to debug. 
Intuitively, our designs do not affect parallel mode. Maybe run out of memory?

**Comment by g0kkk** [comment]
Thank you for your response. I was able to fix it, and one of the reasons, as you mentioned was running out of memory.
